### ISSUE TITLE
Rojo live-syncing breaks Net

### ISSUE THREAD

**Issue by ATK422** [YetAnotherClown/YetAnotherNet#4]
The issue is that the parent of the remote event is under the script, which Rojo overwrites.
To fix this simply move the replicated event outside of the script and somewhere where Rojo can't touch it.
I'll draft a PR tomorrow unless someone else wants to do this.

**Comment by YetAnotherClown** [comment]
Resolved in [Commit 56a4445](https://github.com/YetAnotherClown/Net/commit/56a4445c26981a9172c744e5b7c57b20c72ee44f).
