### ISSUE TITLE
Matter setup routes does not compile in roblox-ts

### ISSUE THREAD

**Issue by littletsu** [YetAnotherClown/YetAnotherNet#8]
In the typescript [documentation for Matter setup](https://yetanotherclown.github.io/Net/docs/setup/matter) the following routes.ts is recommended:
```ts
import { Route } from "@rbxts/yetanothernet";

const defaultConfiguration = {
  Channel: "Reliable",
  Event: "default",
}

// Replicate Matter Components
const MatterReplication = new Route(defaultConfiguration);

// Signal that the Player has loaded
const PlayerLoaded: Route<[boolean]> = new Route(defaultConfiguration);

export = {
  MatterReplication: MatterReplication,
  PlayerLoaded: PlayerLoaded,
}
```

This results in the following error by default: `Argument of type '{ Channel: string; Event: string; }' is not assignable to parameter of type 'Configuration'.
  Types of property 'Channel' are incompatible.
    Type 'string' is not assignable to type '"Reliable" | "Unreliable" | undefined'.`

I fixed this by moving the `Configuration` type to the `Net` namespace 
```ts
declare namespace Net {
    const server: "NET_SERVER";
    
    type Configuration = {
        Channel: "Reliable" | "Unreliable" | undefined,
        Event: string | undefined,
    }
...
```
and make the `defaultConfiguration` use this type
```ts
import { Route, Configuration } from "@rbxts/yetanothernet";

const defaultConfiguration: Configuration = {
	Channel: "Reliable",
	Event: "default",
};

// Replicate Matter Components
const MatterReplication = new Route(defaultConfiguration);

// Signal that the Player has loaded
const PlayerLoaded: Route<[boolean]> = new Route(defaultConfiguration);

export = {
	MatterReplication: MatterReplication,
	PlayerLoaded: PlayerLoaded,
};
```

**Comment by YetAnotherClown** [comment]
Your fix looks good for this, would you like to make a PR for this? If not, I can push a fix later today myself.
