### ISSUE TITLE
Incorrect `routes` type in `Net.start` and `Net.createHook` for roblox-ts

### ISSUE THREAD

**Issue by littletsu** [YetAnotherClown/YetAnotherNet#9]
As of now the definition for Net.start is the following:
```ts
    function start<T extends Array<any>>(loop: any, routes: Array<Route<T>>): void
```
This expects an Array, which only allows numeric indexes unlike Luau's tables, it also forces all routes to be the same type `T` and because of this the recommended [matter setup](https://yetanotherclown.github.io/Net/docs/setup/matter) route definition cannot be used:
```ts
import { Route } from "@rbxts/yetanothernet";

const defaultConfiguration = {
  Channel: "Reliable",
  Event: "default",
}

// Replicate Matter Components
const MatterReplication = new Route(defaultConfiguration);

// Signal that the Player has loaded
const PlayerLoaded: Route<[boolean]> = new Route(defaultConfiguration);

export = {
  MatterReplication: MatterReplication,
  PlayerLoaded: PlayerLoaded,
}
```

I fixed this by turning the `routes` Array in the type into an object and removing the type parameter and for this to work we also have to give the Route a default value:
```ts
    // on index.d.ts Route definition
    class Route<T extends Array<any> = Array<any>> {
        public constructor(configuration: Configuration | null);
```
```ts
    // on index.d.ts start definition
    function start(loop: any, routes: {[index: string]: Route}): void
```

**Comment by YetAnotherClown** [comment]
Thanks for pointing this out, it seems that it affects both the `start` and the `createHook` functions.

We should definitely turn the `routes` array into an object, but we shouldn't give `Route` a default value. Instead, we can just give the `Route` type in the function an `<any>` type parameter list.

```ts
function start(loop: any, routes: {[index: string]: Route<any>}): void

// ...

function createHook(routes: {[index: string]: Route<any>}): () => void
```

Feel free to PR this, otherwise I'll fix it later today as well as your other issue.

**Comment by daphnelucia** [comment]
Yeah that seems like a far better alternative, I've made a PR for both issues in #10
